### ISSUE TITLE
By default no character is spawning and showing body and bomb 1/0 in home scene after latest package update

### ISSUE THREAD

**Issue by pandey623** [suriyun-production/bomber-io-docs#1]

**Comment by insthync** [comment]
Which version of package PUN2 or UNET ?

**Comment by pandey623** [comment]
PUN2

**Comment by insthync** [comment]
When did you update the package, before 8 Nov ?, As I tested on PC and Android, it's still working well.

**Comment by pandey623** [comment]
Yes I updated to the latest package from asset store.
When I am creating fresh project and importing the updated asset. No such issue is coming. But when I am updating the package within my game project which was having older version of the asset. It is not showing up characters during first start of build or editor.

**Comment by MagicRS** [comment]
Up !  I have a same problem

**Comment by pandey623** [comment]
Can you please share fixes for bomber IO as well to test for Bomber IO game asset. Which you have had fixed for shooter IO?

**Comment by insthync** [comment]
Here https://github.com/suriyun-production/bomber-io-docs/issues/2
