### ISSUE TITLE
Assets\BomberIO\Monetization\Scripts\IapProductData.cs(15,12): error CS0246: The type or namespace name 'ProductCatalogItem' could not be found (are you missing a using directive or an assembly reference?)

### ISSUE THREAD

**Issue by Yum1962** [suriyun-production/bomber-io-docs#10]
Assets\BomberIO\Monetization\Scripts\IapProductData.cs(15,12): error CS0246: The type or namespace name 'ProductCatalogItem' could not be found (are you missing a using directive or an assembly reference?)
how to solve? thanks in advance

**Comment by MrBeros** [comment]
Had the same issue. Easy fix....follow the documentation. 

1. New project 
2. Enable Unity Purchase and Ads and import everything needed 
3. Import Adversement package from Package Manager (not sure with the names) 
4. Go to Player settings and add UNITY_PURCHASING;UNITY_ADS
5. Import Bomber.io asset 
6. Should work,  for better explaining, look in the documentation ;)

**Comment by Yum1962** [comment]
@MrBeros  work thanks 👍
