### ISSUE TITLE
Mirror integration

### ISSUE THREAD

**Issue by MrBeros** [suriyun-production/bomber-io-docs#11]
Hey, 
will this asset get a Mirror integration? On the asset store is a steamworks pack which has Mirror support and would work great together with Bomber.io.

**Comment by insthync** [comment]
I won't make Mirror integration because it's like I have to remake it. It's not just bring something to put to the project it's about to change all systems, if I going to makes it work with Steam, I would make a transport layer integration for Steam's networking system.
