### ISSUE TITLE
Facebook button on click no work

### ISSUE THREAD

**Issue by Yum1962** [suriyun-production/bomber-io-docs#14]
integred facebook login put as app id and client token. on click facebook login button nothing works. any ideia to fix it? thanks in advance. no logs in console im confused :S

![login no work](https://user-images.githubusercontent.com/40783613/112003948-1c8a0400-8b00-11eb-9013-47aaa1946508.png)

**Comment by Yum1962** [comment]
setup fb. in dev console setup hashe etc.. any ideia to solve this?

**Comment by Yum1962** [comment]
In fb analitycs show installation. but not works login button :(

**Comment by Yum1962** [comment]
![nologin](https://user-images.githubusercontent.com/40783613/112034970-d9d72480-8b1d-11eb-8436-d219f06b51b4.png)

**Comment by insthync** [comment]
There is no error log in Console?, did you set button's event?

**Comment by Yum1962** [comment]
No errors on the console, in fact no message appears. The defined  button event .. I really don't know what's going on. :(
![button event](https://user-images.githubusercontent.com/40783613/112200935-81bc2300-8bee-11eb-8dda-d0b1879fb3d5.png)

**Comment by Yum1962** [comment]
LoginWithFacebook(1)
LoginWithFacebook(2)

No event button. i m duplicated same for put login backgrounds

**Comment by insthync** [comment]
Try add `PLAYFAB_FB` to scripting define symbols 
![Screenshot_312](https://user-images.githubusercontent.com/2697550/112203122-c5da1280-8c44-11eb-8203-d8d8706bc5fa.png)

**Comment by Yum1962** [comment]
Ok. Works well. and for google play services do i need to add some code in the player settings?

**Comment by insthync** [comment]
PLAYFAB_GPG

**Comment by Yum1962** [comment]
Thanks. Is possible login using facebook on PC/Desktop?

**Comment by insthync** [comment]
I didn't try it too but it should work.
