### ISSUE TITLE
Illegal view ID:0

### ISSUE THREAD

**Issue by RoteXINC** [suriyun-production/bomber-io-docs#17]
Hi!

Tried the new Bomber release (couldnt find the updated changelog) but it gives the Illegal view ID error.
Getting this error when creating a room and joining with another client. (only tried PC right now)

https://puu.sh/I8KMO/7e0bf21f9c.png

Using Unity 2020.1.3f1

Thanks

**Comment by insthync** [comment]
Oh, I will check it.
