### ISSUE TITLE
Github there is no such IO

### ISSUE THREAD

**Issue by FleksisLV** [suriyun-production/bomber-io-docs#19]
I decided to make all important parts to be an open source projects, so you won't have to buy this one, you can find source codes here

Hi ,i was wondering if this is some mistake and why you have write this on all of your IO products that's is free source  but when pressed on github there is no such product

**Comment by insthync** [comment]
Where did you press it? In asset description?

**Comment by FleksisLV** [comment]
Yes

Ittipon Teerapruettikulchai ***@***.***> (šajā datumā:
svētd., 2023. gada 31. dec. 12:04) rakstīja:

**Comment by insthync** [comment]
Here https://github.com/orgs/suriyun-io-games/repositories

**Comment by FleksisLV** [comment]
Thank you very much.

svētd., 2023. g. 31. dec., plkst. 12:08 — lietotājs Ittipon
Teerapruettikulchai ***@***.***>) rakstīja:
