### ISSUE TITLE
[Solved] Problem with the bomb selector

### ISSUE THREAD

**Issue by MagicRS** [suriyun-production/bomber-io-docs#2]
Hello,

When selecting the bombs on the right, it does not change. We see in the "Hierachy" that the prefabs remains on "Bomb01". While all works on the character and the head

I checked the scripts managing the selector but nothing. (UIMainMenu.cs)

thank you in advance
cordially

![image](https://user-images.githubusercontent.com/58114715/69481609-0dfbe180-0e13-11ea-83df-fffc5feb9e67.png)
![image](https://user-images.githubusercontent.com/58114715/69481618-266bfc00-0e13-11ea-8ec0-405f5eb9ac7c.png)

**Comment by insthync** [comment]
Try import this package it may fix your issues
[BomberIOFixInvalidLifeCycle.zip](https://github.com/suriyun-production/bomber-io-docs/files/3882644/BomberIOFixInvalidLifeCycle.zip)

**Comment by MagicRS** [comment]
> Try import this package it may fix your issues
> [BomberIOFixInvalidLifeCycle.zip](https://github.com/suriyun-production/bomber-io-docs/files/3882644/BomberIOFixInvalidLifeCycle.zip)

Thank you very much, but that didn't change anything.
(I imported the 2 scripts contained)

**Comment by MagicRS** [comment]
> > Try import this package it may fix your issues
> > [BomberIOFixInvalidLifeCycle.zip](https://github.com/suriyun-production/bomber-io-docs/files/3882644/BomberIOFixInvalidLifeCycle.zip)
> 
> Thank you very much, but that didn't change anything.
> (I imported the 2 scripts contained)

But the permanent error that targeted this line:
      
Line 99 107 -> Now   textSelectCharacter.text = (SelectCharacter + 1) + "/" + (MaxCharacter + 1);

No longer appears, thanks

**Comment by insthync** [comment]
Okay, Try this package

[BomberIOFixBombNotChanges.zip](https://github.com/suriyun-production/bomber-io-docs/files/3882690/BomberIOFixBombNotChanges.zip)

**Comment by insthync** [comment]
Tell me if it's works :)

**Comment by MagicRS** [comment]
It works!! Thank you very much!!
