### ISSUE TITLE
BUG - no asset of bomb and life in deathmatch

### ISSUE THREAD

**Issue by MagicRS** [suriyun-production/bomber-io-docs#3]
hello, 
I think it could be from the last update (or maybe a fake manipulation).
In the deathmatch and team deathmatch modes the bomb and character configurations are all at 0. (No range bonus, no bomb amount bonus, no heart bonus)
While in the "IO Network" mode everyone works well.

Element tested (re-imported):
- GamePlayManager
- All gameplay scripts
- Game instance script
- InGameUI

**character configuration**
![image](https://user-images.githubusercontent.com/58114715/69900107-f9b66800-136f-11ea-83e2-02037966d46d.png)
**Bomb configuration**
![image](https://user-images.githubusercontent.com/58114715/69900114-0b980b00-1370-11ea-9f66-bd2684920632.png)

DeathMatch and Team DeathMatch
![image](https://user-images.githubusercontent.com/58114715/69900084-ca076000-136f-11ea-977d-746062df094c.png)

"IO Nework" game mode (All is good !)
![image](https://user-images.githubusercontent.com/58114715/69900099-e2777a80-136f-11ea-93e7-ae31f7bb1233.png)

thank you in advance

**Comment by insthync** [comment]
I fixing it now, then I will upload patch package here.

**Comment by insthync** [comment]
This is it.
[PhotonBomberIO-FixInvalidCharacterRespawn.zip](https://github.com/suriyun-production/bomber-io-docs/files/3921874/PhotonBomberIO-FixInvalidCharacterRespawn.zip)

**Comment by MagicRS** [comment]
thank you so much ! this is now ok!
