### ISSUE TITLE
The start button in waiting room doesn't work

### ISSUE THREAD

**Issue by MagicRS** [suriyun-production/bomber-io-docs#4]
Hello,

Do not know what this is but the start button in waiting room does not work anymore. May be updating old bug scripts (in all modes of play).

Below some info.

PS : you have to delete the line n ° 45 in DeathMatchNetworkGameRule.cs if not the button leave and exit (waiting room and in games) I do not work.
Line to delete (45) :  "networkManager.StopCoroutine(endMatchCoroutine);"

Start button : 
![image](https://user-images.githubusercontent.com/58114715/70352796-3ef50100-186c-11ea-80a6-918a359fb20c.png)

nothing happens, no error message.
The button is activated (the passage of the mouse is present (highlight))

Hierarchy : 
![image](https://user-images.githubusercontent.com/58114715/70352901-76fc4400-186c-11ea-8bd6-0cba10403418.png)

WaitingRoomUI configuration
![image](https://user-images.githubusercontent.com/58114715/70352946-94311280-186c-11ea-92f5-a68de3ba21f3.png)

**Comment by insthync** [comment]
Delete codes at line 45 in DeathMatchNetworkGameRule.cs not relates to waiting room codes, not sure when you test room creation every other players pressed the ready button yet?

**Comment by MagicRS** [comment]
> Delete codes at line 45 in DeathMatchNetworkGameRule.cs not relates to waiting room codes, not sure when you test room creation every other players pressed the ready button yet?

yes it has nothing to do, it's an indication of another bug.
And I try to start the game alone (so automatically ready) and with a second account ready too

I had deactivated to make up for the fact that the launch of a game does not take into account the fact that all players are ready or not.
But activated or not (as originally) it does not work now. I still look for the source of the problem.

![image](https://user-images.githubusercontent.com/58114715/70364216-e0d81600-188b-11ea-92ff-cbd65015076e.png)

**Comment by insthync** [comment]
Oh, I see your setting `Can Start When Players Ready At Least` is 120, it's means in this room must have at least 120 ready players to allow host to start game.

**Comment by MagicRS** [comment]
> Oh, I see your setting `Can Start When Players Ready At Least` is 120, it's means in this room must have at least 120 ready players to allow host to start game.

Oh, thank you so much I didn't pay attention to your answer. It's solved!
