### ISSUE TITLE
PlayFab problems :/

### ISSUE THREAD

**Issue by Yum1962** [suriyun-production/bomber-io-docs#6]
Assets\PlayfabClientDemo\PlayfabClient\Scripts\PlayfabMonetizationExporter.cs(50,26): error CS0103: The name 'ProductCatalog' does not exist in the current context
![playfaberror](https://user-images.githubusercontent.com/40783613/74795863-d54e9580-52a5-11ea-8679-60d40e3e952c.png)
please help

**Comment by Yum1962** [comment]
how to solve? :(
![playfaberror2](https://user-images.githubusercontent.com/40783613/75071162-94d45f00-54d3-11ea-9ccc-1afe8c1d159a.png)

**Comment by insthync** [comment]
Did you setup IAP system and import [Playfab SDK](https://aka.ms/playfabunitysdkdownload) ?

**Comment by Yum1962** [comment]
yes playfab sdk imported check my screenshots
![configure2](https://user-images.githubusercontent.com/40783613/75088186-abf16c00-5528-11ea-82ae-ff80b4efec2d.png)
![configure1](https://user-images.githubusercontent.com/40783613/75088187-b01d8980-5528-11ea-8309-267edd8ede85.png)

**Comment by Yum1962** [comment]
![CONFIGURE3](https://user-images.githubusercontent.com/40783613/75088418-c24cf700-552b-11ea-87a7-a6128ec24b2c.png)

**Comment by Yum1962** [comment]
Hello I redid the whole process I believe it is now working, thanks for your attention.
![work](https://user-images.githubusercontent.com/40783613/75088737-14901700-5530-11ea-81a8-50380e376126.png)

**Comment by insthync** [comment]
Okay, it's solved, so I will close this .
