### ISSUE TITLE
error on export catalog

### ISSUE THREAD

**Issue by Yum1962** [suriyun-production/bomber-io-docs#7]
NullReferenceException: Object reference not set to an instance of an object
PlayfabMonetizationExporter.ExportCatalog () (at Assets/PlayfabClientDemo/PlayfabClient/Scripts/PlayfabMonetizationExporter.cs:33)
![moneimportplayfab](https://user-images.githubusercontent.com/40783613/75117245-89f20980-564e-11ea-9ca5-f3c4e58e4ec3.png)

how to solve?

**Comment by insthync** [comment]
Try set prices to characters, heads and bombs

**Comment by Yum1962** [comment]
where I add price to the items and another question when adding the catalog the players will receive gold because at the end of a game for example deathmath informs the reward of 3000 gold but the player does not receive it. on the home screen looks like 0

**Comment by Yum1962** [comment]
I didn't add any items, the price is standard

**Comment by Yum1962** [comment]
![products](https://user-images.githubusercontent.com/40783613/75119865-874ede80-5665-11ea-8183-40ea67487f13.png)

**Comment by Yum1962** [comment]
?

**Comment by insthync** [comment]
[PlayfabClientDemo.zip](https://github.com/suriyun-production/bomber-io-docs/files/4257609/PlayfabClientDemo.zip)
Try this package

**Comment by Yum1962** [comment]
`ArgumentNullException: Value cannot be null.
Parameter name: key
System.Collections.Generic.Dictionary`2[TKey,TValue].TryInsert (TKey key, TValue value, System.Collections.Generic.InsertionBehavior behavior) (at <567df3e0919241ba98db88bec4c6696f>:0)
System.Collections.Generic.Dictionary`2[TKey,TValue].set_Item (TKey key, TValue value) (at <567df3e0919241ba98db88bec4c6696f>:0)
PlayfabMonetizationExporter.ExportCatalog () (at Assets/PlayfabClientDemo/PlayfabClient/Scripts/PlayfabMonetizationExporter.cs:100)`

**Comment by insthync** [comment]
Try set `Store ID Overrides`
![Screenshot_47](https://user-images.githubusercontent.com/2697550/75415494-5c62d400-595e-11ea-8bbb-51b953567bcd.png)
![Screenshot_48](https://user-images.githubusercontent.com/2697550/75415503-6258b500-595e-11ea-9e4c-a71dda5fe49e.png)

**Comment by insthync** [comment]
[PlayfabClientDemo.zip](https://github.com/suriyun-production/bomber-io-docs/files/4259692/PlayfabClientDemo.zip)
Or import this package to avoid errors.
