### ISSUE TITLE
NullReferenceException - PhotonTeamsManager.cs

### ISSUE THREAD

**Issue by RoteXINC** [suriyun-production/bomber-io-docs#8]
Hi,

Whenever i leave a game i get this error, tried a fresh install from the store and still same.

![Unity_Obd5EJ6jU3](https://user-images.githubusercontent.com/19187581/91342934-0f13d200-e7dc-11ea-9701-7ecfd8d20af9.png)

Im getting the same error in the Battle.IO aswell.

**Comment by insthync** [comment]
We actually can ignore it, it won't affect gameplay. Or you may add codes to PhotonTeamsManager.cs to avoid the exception

**Comment by RoteXINC** [comment]
Cant really ignore it, getting the same error everytime im ending a match :P

**Comment by RoteXINC** [comment]
Solved this by looking at all your other IO docs! :)

#https://github.com/suriyun-production/battle-io-docs/issues/17
