### ISSUE TITLE
How change 3d character to 2d character ?

### ISSUE THREAD

**Issue by Yum1962** [suriyun-production/bomber-io-docs#9]
How change 3d character to 2d character ?
Thanks in advance

**Comment by Yum1962** [comment]
How to setup 2d character*?

**Comment by insthync** [comment]
It made for 3d games all colliders are 3d colldiers, If you want to keep using 3d colliders then you still have to modify `CharacterEntity` and `CharacterModel` to change how to move and change character's movement animation by direction.
